<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-GCDQ912" ignored="0" name="Default test" tests="17" failures="2" timestamp="19 Aug 2018 10:41:02 GMT" time="1245.026" errors="0">
  <testcase name="TestCase1_LoginPage" time="45.23" classname="TestngMethods.MainTestCaseFile"/>
  <testcase name="TestCase2_SearchListingPage" time="184.356" classname="TestngMethods.MainTestCaseFile"/>
  <testcase name="TestCase3_PDPTestCase" time="85.008" classname="TestngMethods.MainTestCaseFile"/>
  <testcase name="TestCase4_FavoritesAddSelectedToCart" time="48.179" classname="TestngMethods.MainTestCaseFile"/>
  <testcase name="TestCase5_StandardListing" time="88.792" classname="TestngMethods.MainTestCaseFile"/>
  <testcase name="TestCase6_StandardDetail" time="56.039" classname="TestngMethods.MainTestCaseFile"/>
  <testcase name="TestCase7_CartPage" time="58.2" classname="TestngMethods.MainTestCaseFile"/>
  <testcase name="TestCase8_CheckoutProcess" time="83.094" classname="TestngMethods.MainTestCaseFile"/>
  <testcase name="TestCase9_TrackPage" time="124.748" classname="TestngMethods.MainTestCaseFile"/>
  <testcase name="TestCase10_TrackPage" time="29.235" classname="TestngMethods.MainTestCaseFile"/>
  <testcase name="TestCase11_CalendarsPage" time="25.168" classname="TestngMethods.MainTestCaseFile"/>
  <testcase name="TestCase12_PuchaseAnalysis" time="78.302" classname="TestngMethods.MainTestCaseFile"/>
  <testcase name="TestCase13_SavedReports" time="48.531" classname="TestngMethods.MainTestCaseFile"/>
  <testcase name="TestCase14_TrackOrders" time="64.844" classname="TestngMethods.MainTestCaseFile"/>
  <testcase name="TestCase15_TrackQuotes" time="61.111" classname="TestngMethods.MainTestCaseFile"/>
  <testcase name="TestCase16_MainReports" time="75.478" classname="TestngMethods.MainTestCaseFile">
    <failure type="java.lang.AssertionError" message="Failed in class - POMReportsPage">
      <![CDATA[java.lang.AssertionError: Failed in class - POMReportsPage
at org.testng.Assert.fail(Assert.java:96)
at POMMarkITplacePages.POMReportsPage.AssetPage_Functionality(POMReportsPage.java:99)
at TestngMethods.MainTestCaseFile.TestCase16_MainReports(MainTestCaseFile.java:269)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TestCase16_MainReports -->
  <testcase name="TestCase17_FooterPageOpens" time="70.051" classname="TestngMethods.MainTestCaseFile">
    <failure type="java.lang.AssertionError" message="Failed Testcase in class - POMFooter">
      <![CDATA[java.lang.AssertionError: Failed Testcase in class - POMFooter
at org.testng.Assert.fail(Assert.java:96)
at POMMarkITplacePages.POMFooter.Navigate_Footer(POMFooter.java:161)
at TestngMethods.MainTestCaseFile.TestCase17_FooterPageOpens(MainTestCaseFile.java:284)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TestCase17_FooterPageOpens -->
</testsuite> <!-- Default test -->
